# Generated by Django 5.0.6 on 2024-06-16 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_resettoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResetToken',
            new_name='ResetPassword',
        ),
    ]
