# Generated by Django 5.0.6 on 2024-06-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_year', models.CharField(max_length=6)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=50)),
                ('rejection_percentage', models.CharField(max_length=5)),
                ('reason_1', models.CharField(max_length=250)),
                ('reason_2', models.CharField(max_length=250)),
                ('reason_3', models.CharField(max_length=250)),
            ],
        ),
    ]
